### ISSUE TITLE
Error install: drbdmanage-docker-volume.8.gz don't exist

### ISSUE THREAD

**Issue by djerfy** [LINBIT/drbdmanage-docker-volume#1]
Hi,

File `drbd manage-docker-volume.8.gz` don't exist and return an error with:
```bash
running install
running build
running install_data
copying systemd/docker-drbdmanage-plugin.service -> /lib/systemd/system/
copying systemd/docker-drbdmanage-plugin.socket -> /lib/systemd/system/
creating /usr/libexec
creating /usr/libexec/docker
copying drbdmanage-docker-volume -> /usr/libexec/docker/
error: can't copy 'drbdmanage-docker-volume.8.gz': doesn't exist or not a regular file
```

Please read `setup.py` file, fix with add file or remove line 61.

Regards

**Comment by rck** [comment]
Basically we assume that people that use the code from git know what they do. Otherwise use tarballs as released on linbit.com (not the autogenerated ones on github).

You can generate the file via:
- `make drbdmanage-docker-volume.8.gz`
- or start from a release tarball, which you can generate via `make release`

All in all I don't see anything to fix here. I will close this "issue" the next days.

**Comment by djerfy** [comment]
Ok thanks
